doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        "App\\Migrations": "Migrations"

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'migration_versions'

            doctrine_migrations:
  migrations_paths:
    "App\\Migrations": "src/Migrations"